# Generated by Django 4.1 on 2022-08-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buecherei', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ausleihe',
            options={'verbose_name_plural': 'Ausleihe'},
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Autoren'},
        ),
        migrations.AlterModelOptions(
            name='bibliotheksbenutzer',
            options={'verbose_name_plural': 'Bibliotheksbenutzer'},
        ),
        migrations.AlterModelOptions(
            name='buch',
            options={'verbose_name_plural': 'Bücher'},
        ),
        migrations.AlterModelOptions(
            name='verlag',
            options={'verbose_name_plural': 'Verläge'},
        ),
        migrations.RenameField(
            model_name='buch',
            old_name='verlagID',
            new_name='verlag',
        ),
    ]
