# Generated by Django 4.1 on 2022-08-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buecherei', '0002_alter_ausleihe_options_alter_autor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausleihe',
            name='ausleihdatum',
            field=models.DateField(auto_now_add=True),
        ),
    ]
