# Generated by Django 4.1 on 2022-08-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buecherei', '0003_alter_ausleihe_ausleihdatum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausleihe',
            name='rueckgabedatum',
            field=models.DateField(null=True),
        ),
    ]
