# Generated by Django 4.1 on 2022-08-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buecherei', '0005_alter_buch_verlag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ausleihe',
            name='rueckgabedatum',
            field=models.DateField(blank=True, null=True),
        ),
    ]
