# Generated by Django 4.1 on 2022-08-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buecherei', '0006_alter_ausleihe_rueckgabedatum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buch',
            name='autorid',
        ),
        migrations.AddField(
            model_name='autor',
            name='buch',
            field=models.ManyToManyField(blank=True, related_name='autor', to='buecherei.buch'),
        ),
    ]
