# Generated by Django 4.1 on 2022-08-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buecherei', '0007_remove_buch_autorid_autor_buch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='buch',
            field=models.ManyToManyField(blank=True, db_column='isbn', related_name='autor', to='buecherei.buch'),
        ),
    ]
