# Generated by Django 4.1 on 2022-08-26 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buecherei', '0009_remove_autor_buch_buch_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buch',
            old_name='autor',
            new_name='autorid',
        ),
    ]
