# Generated by Django 4.1 on 2022-08-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buecherei', '0010_rename_autor_buch_autorid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buch',
            name='autorid',
        ),
        migrations.AddField(
            model_name='buch',
            name='autor',
            field=models.ManyToManyField(to='buecherei.autor'),
        ),
    ]
